name: nadafa_app
description: تطبيق تنبيه شاحنة النظافة
publish_to: "none"
- name: Add location permission
  run: |
    sed -i '/<manifest/a\    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>' android/app/src/main/AndroidManifest.xml
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2

flutter:
  uses-material-design: true
